language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing needs to be installed"
script:
# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
- docker --version
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend

# Tagging
- docker tag udagram-api-feed kowalskivn/udagram-api-feed:v1
- docker tag udagram-api-user kowalskivn/udagram-api-user:v1
- docker tag udagram-frontend kowalskivn/udagram-frontend:v1
after_success:
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push kowalskivn/udagram-api-feed:v1
- docker push kowalskivn/udagram-api-user:v1
- docker push kowalskivn/udagramfrontend:v1