apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: kowalskivn/udagram-api-feed:lastest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 500m
          envFrom:
            - configMapRef:
                name: udagram-env
            - secretRef:
                name: udagramdb-env
          volumeMounts:
            - mountPath: "/root/.aws"
              name: udagram-aws
      volumes:
        - name: udagram-aws
          configMap:
            name: udagram-aws
