name: ci
'on':
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push udagram-api-feed
        uses: docker/build-push-action@v3
        with:
          context: .
          file: udagram-api-feed/Dockerfile
          push: true
          tags: '${{ secrets.DOCKER_USERNAME }}/udagram-api-feed:latest'
      - name: Build and push udagram-api-user
        uses: docker/build-push-action@v3
        with:
          context: .
          file: udagram-api-user/Dockerfile
          push: true
          tags: '${{ secrets.DOCKER_USERNAME }}/udagram-api-user:latest'
      - name: Build and push udagram-frontend
        uses: docker/build-push-action@v3
        with:
          context: .
          file: udagram-frontend/Dockerfile
          push: true
          tags: '${{ secrets.DOCKER_USERNAME }}/udagram-frontend:latest'
